'use client'

import type { Metadata } from "next";
import { AnimatePresence } from "framer-motion";
import { motion } from "framer-motion"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { usePathname } from "next/navigation";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {

	const pathName = usePathname();

	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<AnimatePresence mode="wait">
					<motion.div
						key={pathName}
						initial={{opacity: 0}}
						animate={{ opacity: 1}}
						exit={{ opacity: 0}}
						transition={{duration: 0.5}}
					>
						{children}
					</motion.div>

				</AnimatePresence>



			</body>
		</html>
	);
}
